export const events = [
  {
    id: '1',
    title: 'Outdoor Yoga Session',
    date: '2024-12-01',
    time: '08:30 AM',
    location: 'Central Park, New York City',
    maxParticipants: 30,
    targetAudience: ['Adults only', 'Residents of NYC'],
  },
  {
    id: '2',
    title: 'Cooking Masterclass',
    date: '2024-12-05',
    time: '03:00 PM',
    location: 'Culinary Studio, Los Angeles',
    maxParticipants: 12,
    targetAudience: ['Women only', 'Residents of California'],
  },
  {
    id: '3',
    title: 'Photography Walk',
    date: '2024-12-03',
    time: '10:00 AM',
    location: 'Golden Gate Bridge, San Francisco',
    maxParticipants: 25,
    targetAudience: ['Adults only', 'All residents'],
  },
  {
    id: '4',
    title: 'Children’s Art Workshop',
    date: '2024-12-07',
    time: '01:00 PM',
    location: 'City Art Center, Seattle',
    maxParticipants: 15,
    targetAudience: ['Kids only', 'Residents of Seattle'],
  },
  {
    id: '5',
    title: 'Evening Meditation',
    date: '2024-12-06',
    time: '07:00 PM',
    location: 'Beachside, Miami',
    maxParticipants: 20,
    targetAudience: ['Adults only', 'Residents of Florida'],
  },
  {
    id: '6',
    title: 'Hiking Adventure',
    date: '2024-12-10',
    time: '06:00 AM',
    location: 'Rocky Mountains, Colorado',
    maxParticipants: 15,
    targetAudience: ['Adults only', 'All residents'],
  },
  {
    id: '7',
    title: 'Gardening Basics',
    date: '2024-12-08',
    time: '11:00 AM',
    location: 'Community Garden, Chicago',
    maxParticipants: 18,
    targetAudience: ['All ages', 'Residents of Chicago'],
  },
  {
    id: '8',
    title: 'Book Club Meetup',
    date: '2024-12-12',
    time: '05:30 PM',
    location: 'Library Hall, Boston',
    maxParticipants: 20,
    targetAudience: ['Adults only', 'Book lovers'],
  },
  {
    id: '9',
    title: 'Dance Workshop',
    date: '2024-12-09',
    time: '02:00 PM',
    location: 'Dance Studio, Houston',
    maxParticipants: 10,
    targetAudience: ['Women only', 'Residents of Houston'],
  },
  {
    id: '10',
    title: 'Tech Talk: AI Trends',
    date: '2024-12-13',
    time: '04:00 PM',
    location: 'Tech Hub, Austin',
    maxParticipants: 50,
    targetAudience: ['Adults only', 'Tech enthusiasts'],
  },
  {
    id: '11',
    title: 'Family Picnic',
    date: '2024-12-15',
    time: '12:00 PM',
    location: 'River Park, Atlanta',
    maxParticipants: 40,
    targetAudience: ['Families', 'Residents of Georgia'],
  },
  {
    id: '12',
    title: 'Music Jam Session',
    date: '2024-12-14',
    time: '07:30 PM',
    location: 'Open Space, Nashville',
    maxParticipants: 15,
    targetAudience: ['Musicians', 'All residents'],
  },
  {
    id: '13',
    title: 'Wellness Retreat',
    date: '2024-12-16',
    time: '08:00 AM',
    location: 'Resort Center, Hawaii',
    maxParticipants: 10,
    targetAudience: ['Adults only', 'Residents of Hawaii'],
  },
  {
    id: '14',
    title: 'Coding Bootcamp',
    date: '2024-12-18',
    time: '09:00 AM',
    location: 'Tech Center, San Diego',
    maxParticipants: 20,
    targetAudience: ['Adults only', 'Aspiring programmers'],
  },
  {
    id: '15',
    title: 'Poetry Reading Night',
    date: '2024-12-17',
    time: '06:30 PM',
    location: 'City Cafe, Denver',
    maxParticipants: 30,
    targetAudience: ['Adults only', 'Literature lovers'],
  },
  {
    id: '16',
    title: 'Cycling Marathon',
    date: '2024-12-20',
    time: '07:00 AM',
    location: 'City Roads, Philadelphia',
    maxParticipants: 100,
    targetAudience: ['All ages', 'Residents of Pennsylvania'],
  },
  {
    id: '17',
    title: 'Christmas Craft Fair',
    date: '2024-12-21',
    time: '10:00 AM',
    location: 'Main Square, Portland',
    maxParticipants: 50,
    targetAudience: ['All ages', 'Residents of Portland'],
  },
  {
    id: '18',
    title: 'Martial Arts Training',
    date: '2024-12-22',
    time: '03:00 PM',
    location: 'Sports Hall, Dallas',
    maxParticipants: 20,
    targetAudience: ['Adults only', 'Residents of Texas'],
  },
  {
    id: '19',
    title: 'Winter Ski Camp',
    date: '2024-12-23',
    time: '09:00 AM',
    location: 'Mountain Resort, Aspen',
    maxParticipants: 25,
    targetAudience: ['Families', 'Residents of Colorado'],
  },
  {
    id: '20',
    title: 'Workshop',
    date: '2024-12-27',
    time: '11:00 AM',
    location: 'Business Hub, San Francisco',
    maxParticipants: 30,
    targetAudience: ['Adults only', 'Entrepreneurs'],
  },
  {
    id: '21',
    title: 'Charity Run',
    date: '2024-12-30',
    time: '08:00 AM',
    location: 'City Center, Washington DC',
    maxParticipants: 200,
    targetAudience: ['All ages', 'All residents'],
  },
  {
    id: '22',
    title: 'New Year’s Eve Party',
    date: '2024-12-31',
    time: '09:00 PM',
    location: 'Event Hall, Las Vegas',
    maxParticipants: 100,
    targetAudience: ['Adults only', 'Party enthusiasts'],
  },
];
